### PR TITLE
Integration Tests

### PR DESCRIPTION
**Pull request by cursedcoder**
On my fork it is 2.0.3, so you can check the build: 

https://travis-ci.org/cursedcoder/pixi-sound/builds/270715934

browserify&webpack are failing and vanillajs works

And 2.0.4 build is green:

https://travis-ci.org/pixijs/pixi-sound/builds/270715948

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Made a few tweaks to this PR. My biggest concern is weight, **checkpack** is pretty non-trivial because of all the dependencies required, including Chrome. But the functionality is probably worth it. Let me sit on this for a bit.

Also, I would really like to see the output improved for **checkpack**. Better color-coding on successful, opt-in displaying spam/verbose logs and clean-up of cryptic stack traces. Might make a PR for some of these improvements.

**Comment by cursedcoder** [comment]
@bigtimebuddy makes sense.

You could use it for travis-only via global install so DX won't suffer from heavy dependencies.

Indeed it's a new library and contributions are always welcomed.

But checkpack missing more valuable functions such as assert. That's good if your integration doesn't produce errors, on other hand still very important to know if a sound has been played.

**Comment by ivanpopelyshev** [comment]
/me appears from the woods

84 MB!!!!

/me runs back

**Comment by cursedcoder** [comment]
@bigtimebuddy anyway it seems checkpack can be used widely for js projects, so I'm interested in making it better.

Please open as many tickets as you wish and I can get my hands on it.

**Comment by bigtimebuddy** [comment]
Will do!

**Comment by bigtimebuddy** [comment]
Made the integrations primarily run on Travis and **checkpack** won't be installed locally when doing `npm install`, it's only installed when running `npm run integrations`. Thanks for your work on this @cursedcoder.

**Comment by ivanpopelyshev** [comment]
This is awesome.

**Pull request merged**
